services:
  front:
    build: /home/wewiki/app/front
    expose:
      - 80
    networks:
      - wewiki_network

  back:
    build: /home/wewiki/app/back
    expose:
      - 80
    networks:
      - wewiki_network

  db:
    build: /home/wewiki/app/db
    expose:
      - 5432
    networks:
      - wewiki_network
    volumes:
      - db:/var/lib/postgresql/data

  nginx:
    build: /home/wewiki/app/nginx
    tty: true
    ports:
      - 80:80
      - 443:443
    networks:
      - wewiki_network

networks:
  wewiki_network: {}


volumes:
  # front:
  #   driver_opts:
  #     type: volume
  #     o: bind
  #     device: /home/wewiki/app/front/srcs/
  # back:
  #   driver_opts:
  #     type: volume
  #     o: bind
  #     device: /home/wewiki/app/back/srcs/

      # device: /Users/seojin/goinfre/wewiki/app/front/
      # device: /Users/seojin/goinfre
      # device: /Users/jinseongmin/Desktop/workshop/wewiki/app/front/srcs
  db:
    driver_opts:
      type: volume
      o: bind
      device: /home/wewiki/app/db/srcs/
      # device: /Users/seojin/goinfre/wewiki/app/db/srcs