services:
  front:
    build: /home/wewiki/app/front
    expose:
      - 80
    networks:
      - wewiki_network
    # volumes:
    #   - front:/usr/src

  back:
    build: /home/wewiki/app/back
    expose:
      - 80
    networks:
      - wewiki_network

  db:
    build: /home/wewiki/app/db
    expose:
      - 5432
    networks:
      - wewiki_network
    volumes:
      - db:/var/lib/postgresql/data

  nginx:
    build: /home/wewiki/app/nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - wewiki_network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./app/certbot/conf:/etc/letsencrypt
      - ./app/certbot/www:/var/www/certbot
    # volumes:
    #   - front:/usr/share/nginx/html
  certbot:
    image: certbot
    volumes:
      - ./app/certbot/conf:/etc/letsencrypt
      - ./app/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  wewiki_network: {}


volumes:
  # front:
  #   driver_opts:
  #     type: volume
  #     o: bind
  #     device: /home/wewiki/app/front/srcs/
  # back:
  #   driver_opts:
  #     type: volume
  #     o: bind
  #     device: /home/wewiki/app/back/srcs/

      # device: /Users/seojin/goinfre/wewiki/app/front/
      # device: /Users/seojin/goinfre
      # device: /Users/jinseongmin/Desktop/workshop/wewiki/app/front/srcs
  db:
    driver_opts:
      type: volume
      o: bind
      device: /home/wewiki/app/db/srcs/
      # device: /Users/seojin/goinfre/wewiki/app/db/srcs