services:
  front:
    build: /home/wewiki/app/front
    expose:
      - 80
    networks:
      - wewiki_network
    # volumes:
    #   - front:/usr/src

  back:
    build: /home/wewiki/app/back
    expose:
      - 80
    networks:
      - wewiki_network
    # volumes:
    #   - back:/usr/src

  db:
    build: /home/wewiki/app/db
    expose:
      - 5432
    networks:
      - wewiki_network
    volumes:
      - db:/var/lib/pgsql/data

  nginx:
    build: /home/wewiki/app/nginx
    ports:
      - 80:80
    networks:
      - wewiki_network
    # volumes:
    #   - front:/usr/share/nginx/html

networks:
  wewiki_network: {}


volumes:
  # front:
  #   driver_opts:
  #     type: volume
  #     o: bind
  #     device: /home/wewiki/app/front/srcs/
  # back:
  #   driver_opts:
  #     type: volume
  #     o: bind
  #     device: /home/wewiki/app/back/srcs/

      # device: /Users/seojin/goinfre/wewiki/app/front/
      # device: /Users/seojin/goinfre
      # device: /Users/jinseongmin/Desktop/workshop/wewiki/app/front/srcs
  db:
    driver_opts:
      type: volume
      o: bind
      device: /home/wewiki/app/db/srcs/
      # device: /Users/seojin/goinfre/wewiki/app/db/srcs